import re
import os

pl_keys = {
    'tabPersonalization': 'Personalizacja',
    'tabPrivacy': 'Prywatność',
    'tabSystem': 'System',
    'tabSecurity': 'Bezpieczeństwo',
    'testVoiceText': 'Testuję ustawienia głosu. Mam nadzieję, że brzmię dobrze.',
    'settingsTitle': 'Ustawienia Systemowe',
    'settingsSubtitle': 'Konfiguracja środowiska OmniDash',
    'appearanceTitle': 'Wygląd i Personalizacja',
    'userNameLabel': 'Imię / Pseudonim',
    'userNameDesc': 'Twoja nazwa, której asystent AI używa zwracając się do Ciebie.',
    'userNamePlaceholder': 'Wpisz imię...',
    'languageDesc': 'Zmiana języka całego interfejsu i agenta AI.',
    'appThemeLabel': 'Motyw Aplikacji',
    'appThemeDesc': 'Dark Sci-Fi lub jasny tryb produktywny',
    'accentColorLabel': 'Kolor Akcentu',
    'widgetCatalogTitle': 'Katalog Widżetów (Widoczność)',
    'tokenTrackerDesc': 'Zużycie API tokenów.',
    'modelStatusDesc': 'Ping i specyfikacja LLM.',
    'promptVaultDesc': 'Biblioteka gotowych zapytań.',
    'agentQueueDesc': 'Kolejka zadań w tle.',
    'sysMonitorDesc': 'Moduł metryk sprzętowych.',
    'networkMonitorDesc': 'Śledzenie opóźnień sieciowych.',
    'cryptoTrackerDesc': 'Notowania kryptowalut.',
    'scratchpadDesc': 'Twój lokalny notatnik hakerski.',
    'sysMonitorConfigTitle': 'System Monitor (Konfiguracja Pasków)',
    'cpuLabel': 'Wskaźnik CPU',
    'cpuDesc': 'Pokaż zużycie procesora.',
    'ramLabel': 'Wskaźnik RAM',
    'ramDesc': 'Pokaż zużycie pamięci operacyjnej.',
    'uptimeLabel': 'Wskaźnik Uptime',
    'uptimeDesc': 'Pokaż czas od uruchomienia systemu.',
    'newsPrefsTitle': 'Preferencje Kanału IT News',
    'newsPrefsDesc': 'Wybierz kategorie widoczne w widżecie IT Intel Feed. Minimum jedna kategoria.',
    'newsPrefsSaved': '✓ ZAPISANO PREFERENCJE',
    'newsPrefsSave': 'ZAPISZ PREFERENCJE NEWSÓW',
    'privacyTitle': 'Prywatność i Bezpieczeństwo',
    'ghostModeLabel': 'Tryb Ghost (Incognito)',
    'ghostModeDesc': 'Dezaktywuje trwałe zapisywanie logów i historii konwersacji czatu AI. Czat po wyjściu z OmniDash zresetuje się.',
    'storageTitle': 'Zarządzanie Pamięcią',
    'clearCacheLabel': 'Wyczyszczenie Pamięci Podręcznej',
    'clearCacheDesc': 'Trwale usuwa pliki tymczasowe, indeksy i historię czatu.',
    'cacheClearedMsg': 'Pamięć i historia czatu zostały wyczyszczone.',
    'purgeCacheBtn': 'PURGE CACHE',
    'sysPrefsTitle': 'Preferencje Systemowe',
    'soundNotifsLabel': 'Powiadomienia Dźwiękowe',
    'soundNotifsDesc': 'Sygnały audio przy zakończeniu procesów w tle.',
    'voiceAssistantTitle': 'Asystent Głosowy',
    'voiceSelectLabel': 'Wybór Głosu',
    'testVoiceBtn': 'Testuj głos',
    'voiceSelectDesc': 'Wybierz płeć głosu asystenta.',
    'voiceFemale': 'Głos Damski (Paulina/Zofia)',
    'voiceMale': 'Głos Męski (Marek/Adam)',
    'voiceRateLabel': 'Prędkość mowy (Rate):',
    'testRateBtn': 'Testuj prędkość',
    'voiceRateDesc': 'Dostosuj szybkość, z jaką agent odczytuje odpowiedzi.',
    'securityTitle': 'Zabezpieczenia i Autoryzacja',
    'changePinLabel': 'Zmień Kod PIN',
    'changePinDesc': 'Kod ten jest wymagany przy każdym otwarciu OmniDash.',
    'pinUpdatedMsg': 'Zaktualizowano kod PIN!',
    'pinErrorMsg': 'Błąd zmiany PINu: ',
    'oldPinPlaceholder': 'Obecny PIN',
    'newPinPlaceholder': 'Nowy PIN',
    'savePinBtn': 'Zapisz Nowy PIN',
    'factoryResetLabel': 'Reset do Ustawień Fabrycznych',
    'factoryResetDesc': 'Ta operacja usunie wszystkie dane z bazy danych oraz prywatne klucze API. Jest to nieodwracalne.',
    'factoryResetConfirm': 'UWAGA! Czy na pewno chcesz wyczyścić bazę danych i usunąć klucze API? Operacja jest nieodwracalna.',
    'factoryResetDone': 'System zresetowany. Konieczne będzie podanie kluczy przy ponownym uruchomieniu.',
    'factoryResetError': 'Błąd podczas resetowania systemu: ',
    'factoryResetBtn': 'FACTORY RESET',
    
    # Setup Wizard
    'userNameSetupTitle': 'Twoje Imię / Pseudonim',
    'userNameSetupPlaceholder': 'np. Twój pseudonim',
    'appThemeSetupTitle': 'Motyw Aplikacji',
    'mainColorSetupTitle': 'Kolor Główny',
    'catItTech': 'IT & Tech',
    'catScience': 'Świat i Nauka',
    'catLifestyle': 'Rozrywka i Lifestyle',
    'modulesSetupTitle': 'Moduły Ekranu Głównego',
    'backBtn': 'Wstecz',
    'nextBtn': 'DALEJ'
}

en_keys = {
    'tabPersonalization': 'Personalization',
    'tabPrivacy': 'Privacy',
    'tabSystem': 'System',
    'tabSecurity': 'Security',
    'testVoiceText': 'Testing voice settings. I hope I sound good.',
    'settingsTitle': 'System Settings',
    'settingsSubtitle': 'OmniDash environment configuration',
    'appearanceTitle': 'Appearance & Personalization',
    'userNameLabel': 'Name / Nickname',
    'userNameDesc': 'The name your AI assistant will use to address you.',
    'userNamePlaceholder': 'Enter name...',
    'languageDesc': 'Change interface and AI agent language.',
    'appThemeLabel': 'App Theme',
    'appThemeDesc': 'Dark Sci-Fi or Light Productivity mode',
    'accentColorLabel': 'Accent Color',
    'widgetCatalogTitle': 'Widget Catalog (Visibility)',
    'tokenTrackerDesc': 'API token usage.',
    'modelStatusDesc': 'Ping and LLM specification.',
    'promptVaultDesc': 'Library of ready-to-use prompts.',
    'agentQueueDesc': 'Background task queue.',
    'sysMonitorDesc': 'Hardware metrics module.',
    'networkMonitorDesc': 'Network latency tracking.',
    'cryptoTrackerDesc': 'Cryptocurrency quotes.',
    'scratchpadDesc': 'Your local hacker notepad.',
    'sysMonitorConfigTitle': 'System Monitor (Bar Config)',
    'cpuLabel': 'CPU Indicator',
    'cpuDesc': 'Show processor usage.',
    'ramLabel': 'RAM Indicator',
    'ramDesc': 'Show memory usage.',
    'uptimeLabel': 'Uptime Indicator',
    'uptimeDesc': 'Show system uptime.',
    'newsPrefsTitle': 'IT News Feed Preferences',
    'newsPrefsDesc': 'Select categories visible in the IT Intel Feed widget. Minimum one category.',
    'newsPrefsSaved': '✓ PREFERENCES SAVED',
    'newsPrefsSave': 'SAVE NEWS PREFERENCES',
    'privacyTitle': 'Privacy & Security',
    'ghostModeLabel': 'Ghost Mode (Incognito)',
    'ghostModeDesc': 'Disables persistent saving of logs and AI chat history. Chat resets on exit.',
    'storageTitle': 'Storage Management',
    'clearCacheLabel': 'Clear Cache',
    'clearCacheDesc': 'Permanently deletes temporary files, indexes, and chat history.',
    'cacheClearedMsg': 'Cache and chat history have been cleared.',
    'purgeCacheBtn': 'PURGE CACHE',
    'sysPrefsTitle': 'System Preferences',
    'soundNotifsLabel': 'Sound Notifications',
    'soundNotifsDesc': 'Audio signals upon completion of background processes.',
    'voiceAssistantTitle': 'Voice Assistant',
    'voiceSelectLabel': 'Voice Selection',
    'testVoiceBtn': 'Test voice',
    'voiceSelectDesc': 'Select the AI assistant\'s voice gender.',
    'voiceFemale': 'Female Voice (Paulina/Zofia)',
    'voiceMale': 'Male Voice (Marek/Adam)',
    'voiceRateLabel': 'Speech Rate:',
    'testRateBtn': 'Test rate',
    'voiceRateDesc': 'Adjust the speed at which the agent reads responses.',
    'securityTitle': 'Security & Authorization',
    'changePinLabel': 'Change PIN Code',
    'changePinDesc': 'This code is required every time you open OmniDash.',
    'pinUpdatedMsg': 'PIN code updated!',
    'pinErrorMsg': 'Error changing PIN: ',
    'oldPinPlaceholder': 'Current PIN',
    'newPinPlaceholder': 'New PIN',
    'savePinBtn': 'Save New PIN',
    'factoryResetLabel': 'Factory Reset',
    'factoryResetDesc': 'This operation will remove all data from the database and private API keys. It is irreversible.',
    'factoryResetConfirm': 'WARNING! Are you sure you want to clear the database and remove API keys? This operation is irreversible.',
    'factoryResetDone': 'System reset. You will need to provide keys upon next startup.',
    'factoryResetError': 'Error resetting system: ',
    'factoryResetBtn': 'FACTORY RESET',
    
    'userNameSetupTitle': 'Your Name / Nickname',
    'userNameSetupPlaceholder': 'e.g., Your nickname',
    'appThemeSetupTitle': 'App Theme',
    'mainColorSetupTitle': 'Main Color',
    'catItTech': 'IT & Tech',
    'catScience': 'World & Science',
    'catLifestyle': 'Entertainment & Lifestyle',
    'modulesSetupTitle': 'Home Screen Modules',
    'backBtn': 'Back',
    'nextBtn': 'NEXT'
}

uk_keys = {
    'tabPersonalization': 'Персоналізація',
    'tabPrivacy': 'Приватність',
    'tabSystem': 'Система',
    'tabSecurity': 'Безпека',
    'testVoiceText': 'Тестую налаштування голосу. Сподіваюся, я звучу добре.',
    'settingsTitle': 'Системні налаштування',
    'settingsSubtitle': 'Конфігурація середовища OmniDash',
    'appearanceTitle': 'Вигляд і персоналізація',
    'userNameLabel': 'Ім\'я / Псевдонім',
    'userNameDesc': 'Ім\'я, яке ваш ШІ-асистент використовуватиме для звернення до вас.',
    'userNamePlaceholder': 'Введіть ім\'я...',
    'languageDesc': 'Зміна мови інтерфейсу та ШІ-агента.',
    'appThemeLabel': 'Тема додатку',
    'appThemeDesc': 'Dark Sci-Fi або світлий продуктивний режим',
    'accentColorLabel': 'Колір акценту',
    'widgetCatalogTitle': 'Каталог віджетів (Видимість)',
    'tokenTrackerDesc': 'Використання токенів API.',
    'modelStatusDesc': 'Пінг та специфікація LLM.',
    'promptVaultDesc': 'Бібліотека готових запитів.',
    'agentQueueDesc': 'Черга фонових завдань.',
    'sysMonitorDesc': 'Модуль апаратних метрик.',
    'networkMonitorDesc': 'Відстеження затримки мережі.',
    'cryptoTrackerDesc': 'Котирування криптовалют.',
    'scratchpadDesc': 'Ваш локальний хакерський блокнот.',
    'sysMonitorConfigTitle': 'Монітор системи (Конфігурація панелей)',
    'cpuLabel': 'Індикатор CPU',
    'cpuDesc': 'Показати використання процесора.',
    'ramLabel': 'Індикатор RAM',
    'ramDesc': 'Показати використання пам\'яті.',
    'uptimeLabel': 'Індикатор Uptime',
    'uptimeDesc': 'Показати час роботи системи.',
    'newsPrefsTitle': 'Налаштування стрічки IT-новин',
    'newsPrefsDesc': 'Виберіть категорії, видимі у віджеті IT Intel Feed. Мінімум одна категорія.',
    'newsPrefsSaved': '✓ НАЛАШТУВАННЯ ЗБЕРЕЖЕНО',
    'newsPrefsSave': 'ЗБЕРЕГТИ НАЛАШТУВАННЯ НОВИН',
    'privacyTitle': 'Приватність і безпека',
    'ghostModeLabel': 'Режим Ghost (Інкогніто)',
    'ghostModeDesc': 'Вимикає постійне збереження логів та історії чатів ШІ. Чат скидається при виході.',
    'storageTitle': 'Управління пам\'яттю',
    'clearCacheLabel': 'Очистити кеш',
    'clearCacheDesc': 'Назавжди видаляє тимчасові файли, індекси та історію чатів.',
    'cacheClearedMsg': 'Кеш та історію чату очищено.',
    'purgeCacheBtn': 'ОЧИСТИТИ КЕШ',
    'sysPrefsTitle': 'Системні налаштування',
    'soundNotifsLabel': 'Звукові сповіщення',
    'soundNotifsDesc': 'Аудіосигнали при завершенні фонових процесів.',
    'voiceAssistantTitle': 'Голосовий асистент',
    'voiceSelectLabel': 'Вибір голосу',
    'testVoiceBtn': 'Тестувати голос',
    'voiceSelectDesc': 'Виберіть стать голосу ШІ-асистента.',
    'voiceFemale': 'Жіночий голос (Paulina/Zofia)',
    'voiceMale': 'Чоловічий голос (Marek/Adam)',
    'voiceRateLabel': 'Швидкість мови:',
    'testRateBtn': 'Тестувати швидкість',
    'voiceRateDesc': 'Налаштуйте швидкість, з якою агент читає відповіді.',
    'securityTitle': 'Безпека та авторизація',
    'changePinLabel': 'Змінити PIN-код',
    'changePinDesc': 'Цей код потрібен щоразу при відкритті OmniDash.',
    'pinUpdatedMsg': 'PIN-код оновлено!',
    'pinErrorMsg': 'Помилка зміни PIN-коду: ',
    'oldPinPlaceholder': 'Поточний PIN',
    'newPinPlaceholder': 'Новий PIN',
    'savePinBtn': 'Зберегти новий PIN',
    'factoryResetLabel': 'Скидання до заводських налаштувань',
    'factoryResetDesc': 'Ця операція видалить усі дані з бази даних та приватні ключі API. Вона є незворотною.',
    'factoryResetConfirm': 'УВАГА! Ви впевнені, що хочете очистити базу даних і видалити ключі API? Ця операція є незворотною.',
    'factoryResetDone': 'Систему скинуто. Вам потрібно буде надати ключі при наступному запуску.',
    'factoryResetError': 'Помилка скидання системи: ',
    'factoryResetBtn': 'FACTORY RESET',
    
    'userNameSetupTitle': 'Ваше ім\'я / Псевдонім',
    'userNameSetupPlaceholder': 'напр., Ваш псевдонім',
    'appThemeSetupTitle': 'Тема додатку',
    'mainColorSetupTitle': 'Головний колір',
    'catItTech': 'IT та технології',
    'catScience': 'Світ і наука',
    'catLifestyle': 'Розваги та стиль життя',
    'modulesSetupTitle': 'Модулі головного екрану',
    'backBtn': 'Назад',
    'nextBtn': 'ДАЛІ'
}

zh_keys = {
    'tabPersonalization': '个性化',
    'tabPrivacy': '隐私',
    'tabSystem': '系统',
    'tabSecurity': '安全',
    'testVoiceText': '正在测试语音设置。希望我的声音好听。',
    'settingsTitle': '系统设置',
    'settingsSubtitle': 'OmniDash 环境配置',
    'appearanceTitle': '外观和个性化',
    'userNameLabel': '姓名 / 昵称',
    'userNameDesc': '您的 AI 助手用来称呼您的名字。',
    'userNamePlaceholder': '输入名字...',
    'languageDesc': '更改界面和 AI 代理语言。',
    'appThemeLabel': '应用主题',
    'appThemeDesc': '暗黑科幻或明亮生产力模式',
    'accentColorLabel': '强调色',
    'widgetCatalogTitle': '小部件目录 (可见性)',
    'tokenTrackerDesc': 'API 令牌使用情况。',
    'modelStatusDesc': 'Ping 和 LLM 规格。',
    'promptVaultDesc': '现成的提示库。',
    'agentQueueDesc': '后台任务队列。',
    'sysMonitorDesc': '硬件指标模块。',
    'networkMonitorDesc': '网络延迟跟踪。',
    'cryptoTrackerDesc': '加密货币报价。',
    'scratchpadDesc': '您的本地黑客记事本。',
    'sysMonitorConfigTitle': '系统监视器 (栏目配置)',
    'cpuLabel': 'CPU 指示器',
    'cpuDesc': '显示处理器使用情况。',
    'ramLabel': 'RAM 指示器',
    'ramDesc': '显示内存使用情况。',
    'uptimeLabel': '运行时间指示器',
    'uptimeDesc': '显示系统运行时间。',
    'newsPrefsTitle': 'IT 新闻订阅偏好',
    'newsPrefsDesc': '选择在 IT Intel Feed 小部件中可见的类别。至少选择一个类别。',
    'newsPrefsSaved': '✓ 偏好已保存',
    'newsPrefsSave': '保存新闻偏好',
    'privacyTitle': '隐私与安全',
    'ghostModeLabel': '幽灵模式 (无痕)',
    'ghostModeDesc': '禁用持续保存日志和 AI 聊天记录。退出时重置聊天。',
    'storageTitle': '存储管理',
    'clearCacheLabel': '清除缓存',
    'clearCacheDesc': '永久删除临时文件、索引和聊天记录。',
    'cacheClearedMsg': '缓存和聊天记录已清除。',
    'purgeCacheBtn': '清除缓存',
    'sysPrefsTitle': '系统偏好',
    'soundNotifsLabel': '声音通知',
    'soundNotifsDesc': '后台进程完成时的音频信号。',
    'voiceAssistantTitle': '语音助手',
    'voiceSelectLabel': '语音选择',
    'testVoiceBtn': '测试语音',
    'voiceSelectDesc': '选择 AI 助手的语音性别。',
    'voiceFemale': '女声 (Paulina/Zofia)',
    'voiceMale': '男声 (Marek/Adam)',
    'voiceRateLabel': '语速:',
    'testRateBtn': '测试语速',
    'voiceRateDesc': '调整代理读取响应的速度。',
    'securityTitle': '安全与授权',
    'changePinLabel': '更改 PIN 码',
    'changePinDesc': '每次打开 OmniDash 均需输入此代码。',
    'pinUpdatedMsg': 'PIN 码已更新！',
    'pinErrorMsg': '更改 PIN 错误: ',
    'oldPinPlaceholder': '当前 PIN',
    'newPinPlaceholder': '新 PIN',
    'savePinBtn': '保存新 PIN',
    'factoryResetLabel': '恢复出厂设置',
    'factoryResetDesc': '此操作将从数据库和私有 API 密钥中删除所有数据。操作不可逆。',
    'factoryResetConfirm': '警告！您确定要清除数据库并删除 API 密钥吗？此操作不可逆。',
    'factoryResetDone': '系统已重置。下次启动时您需要提供密钥。',
    'factoryResetError': '重置系统错误: ',
    'factoryResetBtn': '恢复出厂设置',
    
    'userNameSetupTitle': '您的姓名 / 昵称',
    'userNameSetupPlaceholder': '例如，您的昵称',
    'appThemeSetupTitle': '应用主题',
    'mainColorSetupTitle': '主题颜色',
    'catItTech': 'IT 与科技',
    'catScience': '世界与科学',
    'catLifestyle': '娱乐与生活方式',
    'modulesSetupTitle': '主屏幕模块',
    'backBtn': '后退',
    'nextBtn': '下一步'
}


settings_replacements = [
    (r"'Personalizacja'", r"t('tabPersonalization', 'Personalizacja')"),
    (r"'Prywatność'", r"t('tabPrivacy', 'Prywatność')"),
    (r"'System'", r"t('tabSystem', 'System')"),
    (r"'Bezpieczeństwo'", r"t('tabSecurity', 'Bezpieczeństwo')"),
    (r'"Ustawienia Systemowe"', r"t('settingsTitle', 'Ustawienia Systemowe')"),
    (r'"Konfiguracja środowiska OmniDash"', r"t('settingsSubtitle', 'Konfiguracja środowiska OmniDash')"),
    (r'"Wygląd i Personalizacja"', r"t('appearanceTitle', 'Wygląd i Personalizacja')"),
    (r'label="Imię / Pseudonim"', r'label={t("userNameLabel", "Imię / Pseudonim")}'),
    (r'desc="Twoja nazwa, której asystent AI używa zwracając się do Ciebie."', r'desc={t("userNameDesc", "Twoja nazwa, której asystent AI używa zwracając się do Ciebie.")}'),
    (r'placeholder="Wpisz imię\.\.\."', r'placeholder={t("userNamePlaceholder", "Wpisz imię...")}'),
    (r'desc="Zmiana języka całego interfejsu i agenta AI\."', r'desc={t("languageDesc", "Zmiana języka całego interfejsu i agenta AI.")}'),
    (r'label="Motyw Aplikacji"', r'label={t("appThemeLabel", "Motyw Aplikacji")}'),
    (r'desc="Dark Sci-Fi lub jasny tryb produktywny"', r'desc={t("appThemeDesc", "Dark Sci-Fi lub jasny tryb produktywny")}'),
    (r'>Kolor Akcentu<', r'>{t("accentColorLabel", "Kolor Akcentu")}<'),
    (r'title="Katalog Widżetów \(Widoczność\)"', r'title={t("widgetCatalogTitle", "Katalog Widżetów (Widoczność)")}'),
    (r'label="Token & Cost Tracker" desc="Zużycie API tokenów\."', r'label="Token & Cost Tracker" desc={t("tokenTrackerDesc", "Zużycie API tokenów.")}'),
    (r'label="Model Status" desc="Ping i specyfikacja LLM\."', r'label="Model Status" desc={t("modelStatusDesc", "Ping i specyfikacja LLM.")}'),
    (r'label="Prompt Vault" desc="Biblioteka gotowych zapytań\."', r'label="Prompt Vault" desc={t("promptVaultDesc", "Biblioteka gotowych zapytań.")}'),
    (r'label="Agent Queue" desc="Kolejka zadań w tle\."', r'label="Agent Queue" desc={t("agentQueueDesc", "Kolejka zadań w tle.")}'),
    (r'label="System Monitor" desc="Moduł metryk sprzętowych\."', r'label="System Monitor" desc={t("sysMonitorDesc", "Moduł metryk sprzętowych.")}'),
    (r'label="Network Monitor" desc="Śledzenie opóźnień sieciowych\."', r'label="Network Monitor" desc={t("networkMonitorDesc", "Śledzenie opóźnień sieciowych.")}'),
    (r'label="Crypto Tracker" desc="Notowania kryptowalut\."', r'label="Crypto Tracker" desc={t("cryptoTrackerDesc", "Notowania kryptowalut.")}'),
    (r'label="Scratchpad" desc="Twój lokalny notatnik hakerski\."', r'label="Scratchpad" desc={t("scratchpadDesc", "Twój lokalny notatnik hakerski.")}'),
    (r'title="System Monitor \(Konfiguracja Pasków\)"', r'title={t("sysMonitorConfigTitle", "System Monitor (Konfiguracja Pasków)")}'),
    (r'label="Wskaźnik CPU" desc="Pokaż zużycie procesora\."', r'label={t("cpuLabel", "Wskaźnik CPU")} desc={t("cpuDesc", "Pokaż zużycie procesora.")}'),
    (r'label="Wskaźnik RAM" desc="Pokaż zużycie pamięci operacyjnej\."', r'label={t("ramLabel", "Wskaźnik RAM")} desc={t("ramDesc", "Pokaż zużycie pamięci operacyjnej.")}'),
    (r'label="Wskaźnik Uptime" desc="Pokaż czas od uruchomienia systemu\."', r'label={t("uptimeLabel", "Wskaźnik Uptime")} desc={t("uptimeDesc", "Pokaż czas od uruchomienia systemu.")}'),
    (r'title="Preferencje Kanału IT News"', r'title={t("newsPrefsTitle", "Preferencje Kanału IT News")}'),
    (r'>Wybierz kategorie widoczne w widżecie IT Intel Feed\. Minimum jedna kategoria\.<', r'>{t("newsPrefsDesc", "Wybierz kategorie widoczne w widżecie IT Intel Feed. Minimum jedna kategoria.")}<'),
    (r"'✓ ZAPISANO PREFERENCJE' : 'ZAPISZ PREFERENCJE NEWSÓW'", r"t('newsPrefsSaved', '✓ ZAPISANO PREFERENCJE') : t('newsPrefsSave', 'ZAPISZ PREFERENCJE NEWSÓW')"),
    (r'title="Prywatność i Bezpieczeństwo"', r'title={t("privacyTitle", "Prywatność i Bezpieczeństwo")}'),
    (r'label="Tryb Ghost \(Incognito\)"', r'label={t("ghostModeLabel", "Tryb Ghost (Incognito)")}'),
    (r'desc="Dezaktywuje trwałe zapisywanie logów i historii konwersacji czatu AI\. Czat po wyjściu z OmniDash zresetuje się\."', r'desc={t("ghostModeDesc", "Dezaktywuje trwałe zapisywanie logów i historii konwersacji czatu AI. Czat po wyjściu z OmniDash zresetuje się.")}'),
    (r'title="Zarządzanie Pamięcią"', r'title={t("storageTitle", "Zarządzanie Pamięcią")}'),
    (r'>Wyczyszczenie Pamięci Podręcznej<', r'>{t("clearCacheLabel", "Wyczyszczenie Pamięci Podręcznej")}<'),
    (r'>Trwale usuwa pliki tymczasowe, indeksy i historię czatu\.<', r'>{t("clearCacheDesc", "Trwale usuwa pliki tymczasowe, indeksy i historię czatu.")}<'),
    (r"alert\('Pamięć i historia czatu zostały wyczyszczone\.'\);", r"alert(t('cacheClearedMsg', 'Pamięć i historia czatu zostały wyczyszczone.'));"),
    (r'>PURGE CACHE<', r'>{t("purgeCacheBtn", "PURGE CACHE")}<'),
    (r'title="Preferencje Systemowe"', r'title={t("sysPrefsTitle", "Preferencje Systemowe")}'),
    (r'label="Powiadomienia Dźwiękowe"', r'label={t("soundNotifsLabel", "Powiadomienia Dźwiękowe")}'),
    (r'desc="Sygnały audio przy zakończeniu procesów w tle\."', r'desc={t("soundNotifsDesc", "Sygnały audio przy zakończeniu procesów w tle.")}'),
    (r'title="Asystent Głosowy"', r'title={t("voiceAssistantTitle", "Asystent Głosowy")}'),
    (r'>Wybór Głosu<', r'>{t("voiceSelectLabel", "Wybór Głosu")}<'),
    (r'>Testuj głos<', r'>{t("testVoiceBtn", "Testuj głos")}<'),
    (r'>Wybierz płeć głosu asystenta\.<', r'>{t("voiceSelectDesc", "Wybierz płeć głosu asystenta.")}<'),
    (r'>Głos Damski \(Paulina/Zofia\)<', r'>{t("voiceFemale", "Głos Damski (Paulina/Zofia)")}<'),
    (r'>Głos Męski \(Marek/Adam\)<', r'>{t("voiceMale", "Głos Męski (Marek/Adam)")}<'),
    (r'>Prędkość mowy \(Rate\): \{voiceRate.toFixed\(1\)\}x<', r'>{t("voiceRateLabel", "Prędkość mowy (Rate):")} {voiceRate.toFixed(1)}x<'),
    (r'>Testuj prędkość<', r'>{t("testRateBtn", "Testuj prędkość")}<'),
    (r'>Dostosuj szybkość, z jaką agent odczytuje odpowiedzi\.<', r'>{t("voiceRateDesc", "Dostosuj szybkość, z jaką agent odczytuje odpowiedzi.")}<'),
    (r'title="Zabezpieczenia i Autoryzacja"', r'title={t("securityTitle", "Zabezpieczenia i Autoryzacja")}'),
    (r'>Zmień Kod PIN<', r'>{t("changePinLabel", "Zmień Kod PIN")}<'),
    (r'>Kod ten jest wymagany przy każdym otwarciu OmniDash\.<', r'>{t("changePinDesc", "Kod ten jest wymagany przy każdym otwarciu OmniDash.")}<'),
    (r"alert\('Zaktualizowano kod PIN!'\);", r"alert(t('pinUpdatedMsg', 'Zaktualizowano kod PIN!'));"),
    (r"alert\('Błąd zmiany PINu: ' \+ \(err\.response\?\.data\?\.error \|\| err\.message\)\);", r"alert(t('pinErrorMsg', 'Błąd zmiany PINu: ') + (err.response?.data?.error || err.message));"),
    (r'placeholder="Obecny PIN"', r'placeholder={t("oldPinPlaceholder", "Obecny PIN")}'),
    (r'placeholder="Nowy PIN"', r'placeholder={t("newPinPlaceholder", "Nowy PIN")}'),
    (r'>Zapisz Nowy PIN<', r'>{t("savePinBtn", "Zapisz Nowy PIN")}<'),
    (r'>Reset do Ustawień Fabrycznych<', r'>{t("factoryResetLabel", "Reset do Ustawień Fabrycznych")}<'),
    (r'>Ta operacja usunie wszystkie dane z bazy danych oraz prywatne klucze API\. Jest to nieodwracalne\.<', r'>{t("factoryResetDesc", "Ta operacja usunie wszystkie dane z bazy danych oraz prywatne klucze API. Jest to nieodwracalne.")}<'),
    (r'window\.confirm\("UWAGA! Czy na pewno chcesz wyczyścić bazę danych i usunąć klucze API\? Operacja jest nieodwracalna\."\)', r'window.confirm(t("factoryResetConfirm", "UWAGA! Czy na pewno chcesz wyczyścić bazę danych i usunąć klucze API? Operacja jest nieodwracalna."))'),
    (r"alert\('System zresetowany\. Konieczne będzie podanie kluczy przy ponownym uruchomieniu\.'\);", r"alert(t('factoryResetDone', 'System zresetowany. Konieczne będzie podanie kluczy przy ponownym uruchomieniu.'));"),
    (r"alert\('Błąd podczas resetowania systemu: ' \+ err\.message\);", r"alert(t('factoryResetError', 'Błąd podczas resetowania systemu: ') + err.message);"),
    (r'>FACTORY RESET<', r'>{t("factoryResetBtn", "FACTORY RESET")}<'),
    (r'"Testuję ustawienia głosu. Mam nadzieję, że brzmię dobrze."', r't("testVoiceText", "Testuję ustawienia głosu. Mam nadzieję, że brzmię dobrze.")')
]

setup_replacements = [
    (r'> Twoje Imię / Pseudonim<', r'> {t("userNameSetupTitle", "Twoje Imię / Pseudonim")}<'),
    (r'placeholder="np\. Twój pseudonim"', r'placeholder={t("userNameSetupPlaceholder", "np. Twój pseudonim")}'),
    (r'> Motyw Aplikacji<', r'> {t("appThemeSetupTitle", "Motyw Aplikacji")}<'),
    (r'> Kolor Główny<', r'> {t("mainColorSetupTitle", "Kolor Główny")}<'),
    (r"'IT & Tech', 'Świat i Nauka', 'Rozrywka i Lifestyle'", r"t('catItTech', 'IT & Tech'), t('catScience', 'Świat i Nauka'), t('catLifestyle', 'Rozrywka i Lifestyle')"),
    (r'> Moduły Ekranu Głównego<', r'> {t("modulesSetupTitle", "Moduły Ekranu Głównego")}<'),
    (r'> Wstecz<', r'> {t("backBtn", "Wstecz")}<'),
    (r">DALEJ<", r">{t('nextBtn', 'DALEJ')}<")
]

def replace_in_file(path, replacements):
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    for pattern, replacement in replacements:
        content = re.sub(pattern, replacement, content)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)

replace_in_file('/home/lis/Pulpit/ai-system-dashboard/modules/pages/SettingsPage.jsx', settings_replacements)
replace_in_file('/home/lis/Pulpit/ai-system-dashboard/modules/components/SetupWizard.jsx', setup_replacements)

# Now update i18n.js
import json
with open('/home/lis/Pulpit/ai-system-dashboard/modules/i18n.js', 'r', encoding='utf-8') as f:
    i18n_content = f.read()

def inject_keys(content, lang, new_keys):
    # Find the translation block for lang
    pattern = r'(' + lang + r':\s*\{\s*translation:\s*\{)'
    match = re.search(pattern, content)
    if match:
        start_idx = match.end()
        # Create string of new keys
        keys_str = ""
        for k, v in new_keys.items():
            keys_str += f'\n      "{k}": "{v}",'
        content = content[:start_idx] + keys_str + content[start_idx:]
    return content

i18n_content = inject_keys(i18n_content, 'pl', pl_keys)
i18n_content = inject_keys(i18n_content, 'en', en_keys)
i18n_content = inject_keys(i18n_content, 'uk', uk_keys)
i18n_content = inject_keys(i18n_content, 'zh', zh_keys)

with open('/home/lis/Pulpit/ai-system-dashboard/modules/i18n.js', 'w', encoding='utf-8') as f:
    f.write(i18n_content)

print("Done translating settings, setup wizard, and i18n")
