import re

pl_keys = {
    'termCopyText': 'Kopiuj tekst',
    'termCmdClear': 'Czyści ekran obecnego trybu',
    'termCmdPurge': 'Agresywnie czyści pamięć i ekran',
    'termCmdWorker': 'Przełącza na tryb inżynieryjny',
    'termCmdMentor': 'Przełącza na tryb analityczny',
    'termCmdExport': 'Zapisuje historię czatu do pliku TXT',
    'termCmdPing': 'Sprawdza łączność i opóźnienie',
    'termCmdHelp': 'Wyświetla listę poleceń',
    'termNoSpeech': 'Twoja przegldarka nie obsuguje SpeechRecognition.',
    'termJarvisSpeaks': 'JARVIS // MÓWI',
    'termJarvisListens': 'JARVIS // NASŁUCHUJE',
    'termJarvisWaits': 'JARVIS // OCZEKUJE',
    'termInputWorker': 'Wprowadź komendę...',
    'termInputMentor': 'Wygadaj się...',
    'termThoughts': 'Przemyślenia AI',
    'termInternalLog': 'Wewnętrzny Dziennik',
    'termVoiceRecord': 'Nagrywanie głosowe',
    'termContinuousMode': 'Tryb ciągłej rozmowy',
    'termNoMic': 'Brak dostępu do mikrofonu',
    
    'chatOnlineWorker': 'SYSTEM ONLINE. Oczekuję na polecenia, mordo.',
    'chatOnlineMentor': 'Cześć. Z czym się dzisiaj mierzysz? Chłodna analiza bez słodzenia gwarantowana.',
    'chatMentorActive': 'System Mentor aktywowany. Oczekiwanie na dane wejściowe...',
    'chatMentorReset': 'System Mentor zresetowany. Oczekiwanie na dane wejściowe...',
    'chatHelpMsg': 'Dostępne polecenia systemowe:\\n- /clear - czyści ekran obecnego trybu.\\n- /purge - agresywnie usuwa lokalną historię z pamięci cache i czyści ekran.\\n- /mode [worker|mentor] - przełącza tryb sztucznej inteligencji.\\n- /export - zapisuje log z rozmową do pliku na dysku twardym.\\n- /ping - weryfikuje łączność i opóźnienie do API System.',
    'chatSwitchedWorker': '[*] INFO: Przełączono na tryb inżynieryjny (WORKER).',
    'chatSwitchedMentor': '[*] INFO: Przełączono na tryb analityczny (MENTOR).',
    'chatUnknownMode': '[!] BŁĄD: Nieznany tryb. Użyj: /mode worker lub /mode mentor',
    'chatExportSuccess': '[+] SUCCESS: Pomyślnie wyeksportowano log konwersacji trybu ',
    'chatPurgeWorker': 'SYSTEM ONLINE. Pamięć podręczna całkowicie wyczyszczona.',
    'chatPurgeMentor1': 'Pamięć długoterminowa zresetowana. Czekam na nowe wytyczne.',
    'chatPurgeMentor2': 'System Mentor uruchomiony (PURGED).',
    'chatPing': '[*] INFO: PINGowanie systemu...',
    'chatPingSuccess': '[+] SUCCESS: Połączenie stabilne. Opóźnienie: ',
    'chatPingError': '[!] ERROR: Połączenie niestabilne. Błąd: ',
    'chatUnknownCmd': '[!] BŁĄD: Nieznana komenda ',
    'chatParseErr': 'Błąd parsowania odpowiedzi.',
    'chatConnErr': 'BŁĄD POŁĄCZENIA: ',
    'chatSorryErr': 'Przepraszam, wystąpił błąd połączenia.',
    'chatDone': 'Wykonano: ',
    'chatTimeout': 'BŁĄD POŁĄCZENIA: Serwer niedostępny po 3 próbach. Sprawdź czy backend działa na porcie 5000. ',

    'workNew': 'Nowy Trening',
    'workTitle': 'Dziennik Treningowy',
    'workDesc': 'Zarządzaj swoimi treningami przy pomocy AI.',
    'workSaved': 'Zapisane Treningi',
    'workLast': 'Ostatni Trening',
    'workAISupport': 'Wsparcie AI',
    'workAISupportDesc': 'Poproś Mentora o ułożenie planu. Worker zapisze go automatycznie.',
    'workHistory': 'Historia Treningów',
    'workNoSaved': 'Brak zapisanych treningów.',
    'workTip': 'Porada: Zapytaj Mentora w AI Terminalu o rozpisanie dzisiejszego treningu!',
    'workAddManual': 'Dodaj Ręcznie Trening',
    'workFormTitle': 'Tytuł (np. Klatka i Biceps)',
    'workFormDate': 'Data',
    'workFormType': 'Typ',
    'workTypeStrength': 'Siłowy',
    'workTypeCardio': 'Cardio',
    'workTypeCalisthenics': 'Kalistenika',
    'workTypeStretch': 'Rozciąganie',
    'workTypeOther': 'Inne',
    'workFormDesc': 'Opis / Plan (Opcjonalnie)',
    'workFormDescPlaceholder': 'Przysiady 4x10\\nMartwy Ciąg 3x8...',
    'workCancel': 'Anuluj',
    'workSave': 'Zapisz',

    'osintTitle': 'OSINT Intel',
    'osintDesc': 'Wywiad jawnoźródłowy & Analiza',
    'osintPlaceholder': 'Szefie, prześwietl domenę google.com...',
    'osintScanning': 'SKANOWANIE...',
    'osintRun': 'URUCHOM SKAN',
    'osintTarget': 'CEL:',
    'osintResolved': 'Rozwiązane IP:',
    'osintGeo': 'Geolokalizacja',
    'osintIP': 'IP:',
    'osintCountry': 'Kraj:',
    'osintCity': 'Miasto:',
    'osintOrg': 'Organizacja:',
    'osintCoords': 'Koordynaty:',
    'osintWayback': 'Wayback Machine',
    'osintSnapshotFound': 'Znaleziono Snapshot',
    'osintLastSnap': 'Ostatni zrzut:',
    'osintOpenArchive': 'OTWÓRZ ARCHIWUM',
    'osintNoArchive': 'Brak danych w Archive.org',
    'osintPwned': 'Pwned Passwords (Wycieki)',
    'osintCritical': 'KRYTYCZNE: Hasło wyciekło ',
    'osintTimes': ' razy!',
    'osintPwnedDesc': 'To hasło pojawiło się w znanych, opublikowanych wyciekach danych. Zalecana natychmiastowa zmiana wszędzie tam, gdzie zostało użyte.',
    'osintSafe': 'BEZPIECZNIE: Hasło nie znalezione w bazie wycieków.',
    'osintSafeDesc': 'Hasło nie figuruje w darmowej bazie HIBP. Pamiętaj jednak o zasadach tworzenia silnych haseł.',
    'osintDNS': 'Rekordy DNS (HackerTarget)',
    'osintWhois': 'WHOIS / Rejestr (HackerTarget)',

    'finLoading': 'Wczytywanie finansów...',
    'finSetupTitle': 'Konfiguracja Budżetu',
    'finSetupDesc': 'Złota zasada 50/30/20 pozwala AI inteligentnie zarządzać Twoimi wydatkami.',
    'finIncome': 'Deklarowany Stały Przychód (Miesięczny)',
    'finNeeds': 'Potrzeby (%)',
    'finWants': 'Zachcianki (%)',
    'finSavings': 'Oszczędności (%)',
    'finSaveSettings': 'Zapisz Ustawienia',
    'finSkip': 'Pomiń',
    'finTitle': 'Finanse Inteligentne',
    'finTotal': 'Stan ogólny:',
    'finAdd': 'Dodaj wpis',
    'finBucketNeeds': 'UŻYTEK COMIESIĘCZNY (NEEDS)',
    'finBucketWants': 'ZACHCIANKI (WANTS)',
    'finBucketSavings': 'OSZCZĘDNOŚCI (SAVINGS)',
    'finBucketUnassigned': 'WOLNE ŚRODKI (UNASSIGNED)',
    'finHistory': 'Historia Transakcji',
    'finNoEntries': 'Brak wpisów finansowych.',
    'finNewTrans': 'Nowa Transakcja',
    'finExpense': 'WYDATEK',
    'finIncomeBtn': 'PRZYCHÓD',
    'finAmount': 'Kwota (PLN)',
    'finBucketLabel': 'Kubełek (Bucket)',
    'finOptNeeds': 'Potrzeby (Needs)',
    'finOptWants': 'Zachcianki (Wants)',
    'finOptSavings': 'Oszczędności (Savings)',
    'finCategory': 'Kategoria',
    'finCatPlaceholder': 'np. Jedzenie, Wypłata',
    'finDesc': 'Opis (opcjonalnie)',
    'finDescPlaceholder': 'np. Zakupy w Biedronce',
    'finDate': 'Data'
}

en_keys = {
    'termCopyText': 'Copy text',
    'termCmdClear': 'Clears the current mode screen',
    'termCmdPurge': 'Aggressively clears memory and screen',
    'termCmdWorker': 'Switches to engineering mode',
    'termCmdMentor': 'Switches to analytical mode',
    'termCmdExport': 'Saves chat history to TXT file',
    'termCmdPing': 'Checks connectivity and latency',
    'termCmdHelp': 'Displays the list of commands',
    'termNoSpeech': 'Your browser does not support SpeechRecognition.',
    'termJarvisSpeaks': 'JARVIS // SPEAKING',
    'termJarvisListens': 'JARVIS // LISTENING',
    'termJarvisWaits': 'JARVIS // WAITING',
    'termInputWorker': 'Enter command...',
    'termInputMentor': 'Speak your mind...',
    'termThoughts': 'AI Thoughts',
    'termInternalLog': 'Internal Log',
    'termVoiceRecord': 'Voice recording',
    'termContinuousMode': 'Continuous conversation mode',
    'termNoMic': 'No microphone access',
    
    'chatOnlineWorker': 'SYSTEM ONLINE. Awaiting commands, mate.',
    'chatOnlineMentor': 'Hello. What are you facing today? Cold analysis with no sugarcoating guaranteed.',
    'chatMentorActive': 'System Mentor activated. Awaiting input...',
    'chatMentorReset': 'System Mentor reset. Awaiting input...',
    'chatHelpMsg': 'Available system commands:\\n- /clear - clears current mode screen.\\n- /purge - aggressively removes local history from cache and clears screen.\\n- /mode [worker|mentor] - switches AI mode.\\n- /export - saves conversation log to a file on hard drive.\\n- /ping - verifies connectivity and latency to System API.',
    'chatSwitchedWorker': '[*] INFO: Switched to engineering mode (WORKER).',
    'chatSwitchedMentor': '[*] INFO: Switched to analytical mode (MENTOR).',
    'chatUnknownMode': '[!] ERROR: Unknown mode. Use: /mode worker or /mode mentor',
    'chatExportSuccess': '[+] SUCCESS: Successfully exported conversation log for mode ',
    'chatPurgeWorker': 'SYSTEM ONLINE. Cache completely cleared.',
    'chatPurgeMentor1': 'Long-term memory reset. Awaiting new instructions.',
    'chatPurgeMentor2': 'System Mentor started (PURGED).',
    'chatPing': '[*] INFO: PINGing system...',
    'chatPingSuccess': '[+] SUCCESS: Connection stable. Latency: ',
    'chatPingError': '[!] ERROR: Connection unstable. Error: ',
    'chatUnknownCmd': '[!] ERROR: Unknown command ',
    'chatParseErr': 'Error parsing response.',
    'chatConnErr': 'CONNECTION ERROR: ',
    'chatSorryErr': 'Sorry, a connection error occurred.',
    'chatDone': 'Executed: ',
    'chatTimeout': 'CONNECTION ERROR: Server unreachable after 3 attempts. Check if backend is running on port 5000. ',

    'workNew': 'New Workout',
    'workTitle': 'Workout Log',
    'workDesc': 'Manage your workouts with AI.',
    'workSaved': 'Saved Workouts',
    'workLast': 'Last Workout',
    'workAISupport': 'AI Support',
    'workAISupportDesc': 'Ask Mentor to create a plan. Worker will save it automatically.',
    'workHistory': 'Workout History',
    'workNoSaved': 'No saved workouts.',
    'workTip': 'Tip: Ask Mentor in AI Terminal to schedule today\'s workout!',
    'workAddManual': 'Add Workout Manually',
    'workFormTitle': 'Title (e.g. Chest and Biceps)',
    'workFormDate': 'Date',
    'workFormType': 'Type',
    'workTypeStrength': 'Strength',
    'workTypeCardio': 'Cardio',
    'workTypeCalisthenics': 'Calisthenics',
    'workTypeStretch': 'Stretching',
    'workTypeOther': 'Other',
    'workFormDesc': 'Description / Plan (Optional)',
    'workFormDescPlaceholder': 'Squats 4x10\\nDeadlift 3x8...',
    'workCancel': 'Cancel',
    'workSave': 'Save',

    'osintTitle': 'OSINT Intel',
    'osintDesc': 'Open Source Intelligence & Analysis',
    'osintPlaceholder': 'Boss, scan the domain google.com...',
    'osintScanning': 'SCANNING...',
    'osintRun': 'RUN SCAN',
    'osintTarget': 'TARGET:',
    'osintResolved': 'Resolved IP:',
    'osintGeo': 'Geolocation',
    'osintIP': 'IP:',
    'osintCountry': 'Country:',
    'osintCity': 'City:',
    'osintOrg': 'Organization:',
    'osintCoords': 'Coordinates:',
    'osintWayback': 'Wayback Machine',
    'osintSnapshotFound': 'Snapshot Found',
    'osintLastSnap': 'Last snapshot:',
    'osintOpenArchive': 'OPEN ARCHIVE',
    'osintNoArchive': 'No data in Archive.org',
    'osintPwned': 'Pwned Passwords (Leaks)',
    'osintCritical': 'CRITICAL: Password leaked ',
    'osintTimes': ' times!',
    'osintPwnedDesc': 'This password has appeared in known, published data breaches. Immediate change is recommended wherever used.',
    'osintSafe': 'SAFE: Password not found in leak database.',
    'osintSafeDesc': 'The password is not listed in the free HIBP database. However, remember the rules for creating strong passwords.',
    'osintDNS': 'DNS Records (HackerTarget)',
    'osintWhois': 'WHOIS / Registry (HackerTarget)',

    'finLoading': 'Loading finances...',
    'finSetupTitle': 'Budget Setup',
    'finSetupDesc': 'The 50/30/20 golden rule allows AI to intelligently manage your expenses.',
    'finIncome': 'Declared Fixed Income (Monthly)',
    'finNeeds': 'Needs (%)',
    'finWants': 'Wants (%)',
    'finSavings': 'Savings (%)',
    'finSaveSettings': 'Save Settings',
    'finSkip': 'Skip',
    'finTitle': 'Smart Finances',
    'finTotal': 'Overall Balance:',
    'finAdd': 'Add Entry',
    'finBucketNeeds': 'MONTHLY NEEDS (NEEDS)',
    'finBucketWants': 'DESIRES (WANTS)',
    'finBucketSavings': 'SAVINGS (SAVINGS)',
    'finBucketUnassigned': 'FREE FUNDS (UNASSIGNED)',
    'finHistory': 'Transaction History',
    'finNoEntries': 'No financial entries.',
    'finNewTrans': 'New Transaction',
    'finExpense': 'EXPENSE',
    'finIncomeBtn': 'INCOME',
    'finAmount': 'Amount (PLN)',
    'finBucketLabel': 'Bucket',
    'finOptNeeds': 'Needs',
    'finOptWants': 'Wants',
    'finOptSavings': 'Savings',
    'finCategory': 'Category',
    'finCatPlaceholder': 'e.g. Food, Salary',
    'finDesc': 'Description (Optional)',
    'finDescPlaceholder': 'e.g. Groceries at Walmart',
    'finDate': 'Date'
}

uk_keys = en_keys
zh_keys = en_keys

import json

def update_i18n(lang, keys):
    with open('/home/lis/Pulpit/ai-system-dashboard/modules/i18n.js', 'r', encoding='utf-8') as f:
        content = f.read()
    pattern = r'(' + lang + r':\s*\{\s*translation:\s*\{)'
    match = re.search(pattern, content)
    if match:
        start_idx = match.end()
        keys_str = ""
        for k, v in keys.items():
            keys_str += f'\\n      "{k}": "{v}",'
        content = content[:start_idx] + keys_str + content[start_idx:]
        with open('/home/lis/Pulpit/ai-system-dashboard/modules/i18n.js', 'w', encoding='utf-8') as f:
            f.write(content)

update_i18n('pl', pl_keys)
update_i18n('en', en_keys)
update_i18n('uk', uk_keys)
update_i18n('zh', zh_keys)

def process_component(file_path, replacements):
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Inject import
    if "useTranslation" not in content:
        content = content.replace("import React", "import { useTranslation } from 'react-i18next';\nimport React")

    # Inject hook
    hook = "  const { t } = useTranslation();\n"
    # Find component function def
    # Example: const Component = () => { or const Component = ({ props }) => {
    match = re.search(r'(const \w+\s*=\s*\([^)]*\)\s*=>\s*\{)', content)
    if match and "const { t } = useTranslation();" not in content:
        content = content[:match.end()] + "\n" + hook + content[match.end():]
        
    for k, v in replacements:
        content = content.replace(k, v)
        
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)

terminal_repl = [
    ("'Kopiuj tekst'", "t('termCopyText', 'Kopiuj tekst')"),
    ("'Czyści ekran obecnego trybu'", "t('termCmdClear', 'Czyści ekran obecnego trybu')"),
    ("'Agresywnie czyści pamięć i ekran'", "t('termCmdPurge', 'Agresywnie czyści pamięć i ekran')"),
    ("'Przełącza na tryb inżynieryjny'", "t('termCmdWorker', 'Przełącza na tryb inżynieryjny')"),
    ("'Przełącza na tryb analityczny'", "t('termCmdMentor', 'Przełącza na tryb analityczny')"),
    ("'Zapisuje historię czatu do pliku TXT'", "t('termCmdExport', 'Zapisuje historię czatu do pliku TXT')"),
    ("'Sprawdza łączność i opóźnienie'", "t('termCmdPing', 'Sprawdza łączność i opóźnienie')"),
    ("'Wyświetla listę poleceń'", "t('termCmdHelp', 'Wyświetla listę poleceń')"),
    ('"Twoja przegldarka nie obsuguje SpeechRecognition."', 't("termNoSpeech", "Twoja przeglądarka nie obsługuje SpeechRecognition.")'),
    ("'JARVIS // MÓWI'", "t('termJarvisSpeaks', 'JARVIS // MÓWI')"),
    ("'JARVIS // NASŁUCHUJE'", "t('termJarvisListens', 'JARVIS // NASŁUCHUJE')"),
    ("'JARVIS // OCZEKUJE'", "t('termJarvisWaits', 'JARVIS // OCZEKUJE')"),
    ('"Wprowadź komendę..."', 't("termInputWorker", "Wprowadź komendę...")'),
    ('"Wygadaj się..."', 't("termInputMentor", "Wygadaj się...")'),
    ('title="Przemyślenia AI"', 'title={t("termThoughts", "Przemyślenia AI")}'),
    ('Wewnętrzny Dziennik', '{t("termInternalLog", "Wewnętrzny Dziennik")}'),
    ('title="Nagrywanie gosowe"', 'title={t("termVoiceRecord", "Nagrywanie głosowe")}'),
    ('title="Tryb ciągłej rozmowy"', 'title={t("termContinuousMode", "Tryb ciągłej rozmowy")}'),
    ('"Brak dostępu do mikrofonu"', 't("termNoMic", "Brak dostępu do mikrofonu")'),
]

chat_repl = [
    ("'SYSTEM ONLINE. Oczekuję na polecenia, mordo.'", "t('chatOnlineWorker', 'SYSTEM ONLINE. Oczekuję na polecenia, mordo.')"),
    ("'Cześć. Z czym się dzisiaj mierzysz? Chłodna analiza bez słodzenia gwarantowana.'", "t('chatOnlineMentor', 'Cześć. Z czym się dzisiaj mierzysz? Chłodna analiza bez słodzenia gwarantowana.')"),
    ('"System Mentor aktywowany. Oczekiwanie na dane wejściowe..."', 't("chatMentorActive", "System Mentor aktywowany. Oczekiwanie na dane wejściowe...")'),
    ('"System Mentor zresetowany. Oczekiwanie na dane wejściowe..."', 't("chatMentorReset", "System Mentor zresetowany. Oczekiwanie na dane wejściowe...")'),
    ("`Dostępne polecenia systemowe:\\n- /clear - czyści ekran obecnego trybu.\\n- /purge - agresywnie usuwa lokalną historię z pamięci cache i czyści ekran.\\n- /mode [worker|mentor] - przełącza tryb sztucznej inteligencji.\\n- /export - zapisuje log z rozmową do pliku na dysku twardym.\\n- /ping - weryfikuje łączność i opóźnienie do API System.`", "t('chatHelpMsg', 'Dostępne polecenia systemowe:\\n- /clear - czyści ekran obecnego trybu.\\n- /purge - agresywnie usuwa lokalną historię z pamięci cache i czyści ekran.\\n- /mode [worker|mentor] - przełącza tryb sztucznej inteligencji.\\n- /export - zapisuje log z rozmową do pliku na dysku twardym.\\n- /ping - weryfikuje łączność i opóźnienie do API System.')"),
    ("'[*] INFO: Przełączono na tryb inżynieryjny (WORKER).'", "t('chatSwitchedWorker', '[*] INFO: Przełączono na tryb inżynieryjny (WORKER).')"),
    ("'[*] INFO: Przełączono na tryb analityczny (MENTOR).'", "t('chatSwitchedMentor', '[*] INFO: Przełączono na tryb analityczny (MENTOR).')"),
    ("`[!] BŁĄD: Nieznany tryb. Użyj: /mode worker lub /mode mentor`", "t('chatUnknownMode', '[!] BŁĄD: Nieznany tryb. Użyj: /mode worker lub /mode mentor')"),
    ("`[+] SUCCESS: Pomyślnie wyeksportowano log konwersacji trybu ${mode.toUpperCase()}.`", "t('chatExportSuccess', '[+] SUCCESS: Pomyślnie wyeksportowano log konwersacji trybu ') + mode.toUpperCase()"),
    ("'SYSTEM ONLINE. Pamięć podręczna całkowicie wyczyszczona.'", "t('chatPurgeWorker', 'SYSTEM ONLINE. Pamięć podręczna całkowicie wyczyszczona.')"),
    ("'Pamięć długoterminowa zresetowana. Czekam na nowe wytyczne.'", "t('chatPurgeMentor1', 'Pamięć długoterminowa zresetowana. Czekam na nowe wytyczne.')"),
    ('"System Mentor uruchomiony (PURGED)."', 't("chatPurgeMentor2", "System Mentor uruchomiony (PURGED).")'),
    ("`[*] INFO: PINGowanie systemu...`", "t('chatPing', '[*] INFO: PINGowanie systemu...')"),
    ("`[+] SUCCESS: Połączenie stabilne. Opóźnienie: ${end - start}ms.`", "t('chatPingSuccess', '[+] SUCCESS: Połączenie stabilne. Opóźnienie: ') + (end - start) + 'ms.'"),
    ("`[!] ERROR: Połączenie niestabilne. Błąd: ${err.message}`", "t('chatPingError', '[!] ERROR: Połączenie niestabilne. Błąd: ') + err.message"),
    ("`[!] BŁĄD: Nieznana komenda '${cmd}'. Wpisz /help, aby zobaczyć listę.`", "t('chatUnknownCmd', '[!] BŁĄD: Nieznana komenda ') + cmd + '. Wpisz /help, aby zobaczyć listę.'"),
    ('"Błąd parsowania odpowiedzi."', 't("chatParseErr", "Błąd parsowania odpowiedzi.")'),
    ("`BŁĄD POŁĄCZENIA: ${err.message}`", "t('chatConnErr', 'BŁĄD POŁĄCZENIA: ') + err.message"),
    ('"Przepraszam, wystąpił błąd połączenia."', 't("chatSorryErr", "Przepraszam, wystąpił błąd połączenia.")'),
    ("`Wykonano: ${data.payload.title}`", "t('chatDone', 'Wykonano: ') + data.payload.title"),
    ("`BŁĄD POŁĄCZENIA: Serwer niedostępny po 3 próbach. Sprawdź czy backend działa na porcie 5000. (${lastError?.message})`", "t('chatTimeout', 'BŁĄD POŁĄCZENIA: Serwer niedostępny po 3 próbach. Sprawdź czy backend działa na porcie 5000. ') + '(' + lastError?.message + ')'"),
]

work_repl = [
    ('>Nowy Trening<', '>{t("workNew", "Nowy Trening")}<'),
    ('>Dziennik Treningowy<', '>{t("workTitle", "Dziennik Treningowy")}<'),
    ('>Zarządzaj swoimi treningami przy pomocy AI.<', '>{t("workDesc", "Zarządzaj swoimi treningami przy pomocy AI.")}<'),
    ('>Zapisane Treningi<', '>{t("workSaved", "Zapisane Treningi")}<'),
    ('>Ostatni Trening<', '>{t("workLast", "Ostatni Trening")}<'),
    ('>Wsparcie AI<', '>{t("workAISupport", "Wsparcie AI")}<'),
    ('>Poproś Mentora o ułożenie planu. Worker zapisze go automatycznie.<', '>{t("workAISupportDesc", "Poproś Mentora o ułożenie planu. Worker zapisze go automatycznie.")}<'),
    ('>Historia Treningów<', '>{t("workHistory", "Historia Treningów")}<'),
    ('>Brak zapisanych treningów.<', '>{t("workNoSaved", "Brak zapisanych treningów.")}<'),
    ('>Porada: Zapytaj Mentora w AI Terminalu o rozpisanie dzisiejszego treningu!<', '>{t("workTip", "Porada: Zapytaj Mentora w AI Terminalu o rozpisanie dzisiejszego treningu!")}<'),
    ('>Dodaj Ręcznie Trening<', '>{t("workAddManual", "Dodaj Ręcznie Trening")}<'),
    ('>Tytuł (np. Klatka i Biceps)<', '>{t("workFormTitle", "Tytuł (np. Klatka i Biceps)")}<'),
    ('>Data<', '>{t("workFormDate", "Data")}<'),
    ('>Typ<', '>{t("workFormType", "Typ")}<'),
    ('>Siłowy<', '>{t("workTypeStrength", "Siłowy")}<'),
    ('>Cardio<', '>{t("workTypeCardio", "Cardio")}<'),
    ('>Kalistenika<', '>{t("workTypeCalisthenics", "Kalistenika")}<'),
    ('>Rozciąganie<', '>{t("workTypeStretch", "Rozciąganie")}<'),
    ('>Inne<', '>{t("workTypeOther", "Inne")}<'),
    ('>Opis / Plan (Opcjonalnie)<', '>{t("workFormDesc", "Opis / Plan (Opcjonalnie)")}<'),
    ('placeholder="Przysiady 4x10\\nMartwy Ciąg 3x8..."', 'placeholder={t("workFormDescPlaceholder", "Przysiady 4x10\\nMartwy Ciąg 3x8...")}'),
    ('>Anuluj<', '>{t("workCancel", "Anuluj")}<'),
    ('>Zapisz<', '>{t("workSave", "Zapisz")}<'),
]

osint_repl = [
    ('>OSINT Intel<', '>{t("osintTitle", "OSINT Intel")}<'),
    ('>Wywiad jawnoźródłowy & Analiza<', '>{t("osintDesc", "Wywiad jawnoźródłowy & Analiza")}<'),
    ('placeholder="Szefie, prześwietl domenę google.com..."', 'placeholder={t("osintPlaceholder", "Szefie, prześwietl domenę google.com...")}'),
    ("'SKANOWANIE...'", "t('osintScanning', 'SKANOWANIE...')"),
    ("'URUCHOM SKAN'", "t('osintRun', 'URUCHOM SKAN')"),
    ('CEL: ', '{t("osintTarget", "CEL: ")}'),
    ('Rozwiązane IP: ', '{t("osintResolved", "Rozwiązane IP: ")}'),
    ('>Geolokalizacja<', '>{t("osintGeo", "Geolokalizacja")}<'),
    ('>IP:<', '>{t("osintIP", "IP:")}<'),
    ('>Kraj:<', '>{t("osintCountry", "Kraj:")}<'),
    ('>Miasto:<', '>{t("osintCity", "Miasto:")}<'),
    ('>Organizacja:<', '>{t("osintOrg", "Organizacja:")}<'),
    ('>Koordynaty:<', '>{t("osintCoords", "Koordynaty:")}<'),
    ('>Wayback Machine<', '>{t("osintWayback", "Wayback Machine")}<'),
    ('>Znaleziono Snapshot<', '>{t("osintSnapshotFound", "Znaleziono Snapshot")}<'),
    ('>Ostatni zrzut:<', '>{t("osintLastSnap", "Ostatni zrzut:")}<'),
    ('>OTWÓRZ ARCHIWUM<', '>{t("osintOpenArchive", "OTWÓRZ ARCHIWUM")}<'),
    ('> Brak danych w Archive.org<', '>{t("osintNoArchive", " Brak danych w Archive.org")}<'),
    ('>Pwned Passwords (Wycieki)<', '>{t("osintPwned", "Pwned Passwords (Wycieki)")}<'),
    ('>KRYTYCZNE: Hasło wyciekło {results.hibp} razy!<', '>{t("osintCritical", "KRYTYCZNE: Hasło wyciekło ")}{results.hibp}{t("osintTimes", " razy!")}<'),
    ('>To hasło pojawiło się w znanych, opublikowanych wyciekach danych. Zalecana natychmiastowa zmiana wszędzie tam, gdzie zostało użyte.<', '>{t("osintPwnedDesc", "To hasło pojawiło się w znanych, opublikowanych wyciekach danych. Zalecana natychmiastowa zmiana wszędzie tam, gdzie zostało użyte.")}<'),
    ('>BEZPIECZNIE: Hasło nie znalezione w bazie wycieków.<', '>{t("osintSafe", "BEZPIECZNIE: Hasło nie znalezione w bazie wycieków.")}<'),
    ('>Hasło nie figuruje w darmowej bazie HIBP. Pamiętaj jednak o zasadach tworzenia silnych haseł.<', '>{t("osintSafeDesc", "Hasło nie figuruje w darmowej bazie HIBP. Pamiętaj jednak o zasadach tworzenia silnych haseł.")}<'),
    ('>Rekordy DNS (HackerTarget)<', '>{t("osintDNS", "Rekordy DNS (HackerTarget)")}<'),
    ('>WHOIS / Rejestr (HackerTarget)<', '>{t("osintWhois", "WHOIS / Rejestr (HackerTarget)")}<'),
]

finance_repl = [
    ('>Wczytywanie finansów...<', '>{t("finLoading", "Wczytywanie finansów...")}<'),
    ('>Konfiguracja Budżetu<', '>{t("finSetupTitle", "Konfiguracja Budżetu")}<'),
    ('>Złota zasada 50/30/20 pozwala AI inteligentnie zarządzać Twoimi wydatkami.<', '>{t("finSetupDesc", "Złota zasada 50/30/20 pozwala AI inteligentnie zarządzać Twoimi wydatkami.")}<'),
    ('>Deklarowany Stały Przychód (Miesięczny)<', '>{t("finIncome", "Deklarowany Stały Przychód (Miesięczny)")}<'),
    ('>Potrzeby (%)<', '>{t("finNeeds", "Potrzeby (%)")}<'),
    ('>Zachcianki (%)<', '>{t("finWants", "Zachcianki (%)")}<'),
    ('>Oszczędności (%)<', '>{t("finSavings", "Oszczędności (%)")}<'),
    ('>Zapisz Ustawienia<', '>{t("finSaveSettings", "Zapisz Ustawienia")}<'),
    ('>Pomiń<', '>{t("finSkip", "Pomiń")}<'),
    ('>Finanse Inteligentne<', '>{t("finTitle", "Finanse Inteligentne")}<'),
    ('Stan ogólny: ', '{t("finTotal", "Stan ogólny: ")}'),
    (' Dodaj wpis', ' {t("finAdd", "Dodaj wpis")}'),
    ('>UŻYTEK COMIESIĘCZNY (NEEDS)<', '>{t("finBucketNeeds", "UŻYTEK COMIESIĘCZNY (NEEDS)")}<'),
    ('>ZACHCIANKI (WANTS)<', '>{t("finBucketWants", "ZACHCIANKI (WANTS)")}<'),
    ('>OSZCZĘDNOŚCI (SAVINGS)<', '>{t("finBucketSavings", "OSZCZĘDNOŚCI (SAVINGS)")}<'),
    ('>WOLNE ŚRODKI (UNASSIGNED)<', '>{t("finBucketUnassigned", "WOLNE ŚRODKI (UNASSIGNED)")}<'),
    ('>Historia Transakcji<', '>{t("finHistory", "Historia Transakcji")}<'),
    ('>Brak wpisów finansowych.<', '>{t("finNoEntries", "Brak wpisów finansowych.")}<'),
    ('>Nowa Transakcja<', '>{t("finNewTrans", "Nowa Transakcja")}<'),
    ('>WYDATEK<', '>{t("finExpense", "WYDATEK")}<'),
    ('>PRZYCHÓD<', '>{t("finIncomeBtn", "PRZYCHÓD")}<'),
    ('>Kwota (PLN)<', '>{t("finAmount", "Kwota (PLN)")}<'),
    ('>Kubełek (Bucket)<', '>{t("finBucketLabel", "Kubełek (Bucket)")}<'),
    ('>Potrzeby (Needs)<', '>{t("finOptNeeds", "Potrzeby (Needs)")}<'),
    ('>Zachcianki (Wants)<', '>{t("finOptWants", "Zachcianki (Wants)")}<'),
    ('>Oszczędności (Savings)<', '>{t("finOptSavings", "Oszczędności (Savings)")}<'),
    ('>Kategoria<', '>{t("finCategory", "Kategoria")}<'),
    ('placeholder="np. Jedzenie, Wypłata"', 'placeholder={t("finCatPlaceholder", "np. Jedzenie, Wypłata")}'),
    ('>Opis (opcjonalnie)<', '>{t("finDesc", "Opis (opcjonalnie)")}<'),
    ('placeholder="np. Zakupy w Biedronce"', 'placeholder={t("finDescPlaceholder", "np. Zakupy w Biedronce")}'),
    ('>Data<', '>{t("finDate", "Data")}<')
]

process_component('/home/lis/Pulpit/ai-system-dashboard/modules/components/Terminal.jsx', terminal_repl)
process_component('/home/lis/Pulpit/ai-system-dashboard/modules/context/ChatContext.jsx', chat_repl)
process_component('/home/lis/Pulpit/ai-system-dashboard/modules/pages/WorkoutsPage.jsx', work_repl)
process_component('/home/lis/Pulpit/ai-system-dashboard/modules/pages/OSINTPage.jsx', osint_repl)
process_component('/home/lis/Pulpit/ai-system-dashboard/modules/pages/FinancePage.jsx', finance_repl)
